# generated by Neptune Namespaces
# file: nvc/app/models/index.coffee

module.exports =
Models          = require './namespace'
Models.NavState = require './nav_state'
Models.finishLoad(
  ["NavState"]
)