# generated by Neptune Namespaces
# file: nvc/app/models/namespace.coffee

App = require '../namespace'
module.exports = App.Models ||
class App.Models extends Neptune.Base
  @namespace: App
  @namespacePath: "Neptune.Nvc.App.Models"

App.addNamespace App.Models