# generated by Neptune Namespaces v0.5
# file: nvc/app/models/namespace.coffee

App = require '../namespace'
module.exports = App.Models ||
App.addNamespace 'Models', class Models extends Neptune.Base
  ;