# generated by Neptune Namespaces
# file: nvc/app/components/index.coffee

module.exports =
Components          = require './namespace'
Components.App      = require './app'
Components.TabBar   = require './tab_bar'
Components.Pages    = require './pages'
Components.Partials = require './partials'
Components.finishLoad(
  ["App","TabBar"]
)