# generated by Neptune Namespaces
# file: nvc/app/components/index.coffee

module.exports =
Components       = require './namespace'
Components.Pages = require './pages'
Components.App   = require './app'
Components.finishLoad(
  ["App"]
)