# generated by Neptune Namespaces v1.x.x
# file: nvc/app/components/index.coffee

module.exports = require './namespace'
.addModules
  App:            require './app'           
  Button:         require './Button'        
  CategoryButton: require './CategoryButton'
  LeafButton:     require './LeafButton'    
  ShowMap:        require './ShowMap'       