# generated by Neptune Namespaces v0.5
# file: nvc/app/components/namespace.coffee

App = require '../namespace'
module.exports = App.Components ||
App.addNamespace 'Components', class Components extends Neptune.Base
  ;