# generated by Neptune Namespaces
# file: nvc/app/components/namespace.coffee

App = require '../namespace'
module.exports = App.Components ||
class App.Components extends Neptune.Base
  @namespace: App
  @namespacePath: "Neptune.Nvc.App.Components"

App.addNamespace App.Components