# generated by Neptune Namespaces
# file: nvc/app/components/partials/index.coffee

module.exports =
Partials           = require './namespace'
Partials.TabButton = require './tab_button'
Partials.finishLoad(
  ["TabButton"]
)