# generated by Neptune Namespaces
# file: nvc/app/components/partials/namespace.coffee

Components = require '../namespace'
module.exports = Components.Partials ||
class Components.Partials extends Neptune.Base
  @namespace: Components
  @namespacePath: "Neptune.Nvc.App.Components.Partials"

Components.addNamespace Components.Partials