# generated by Neptune Namespaces v0.3.0
# file: nvc/app/components/partials/namespace.coffee

Components = require '../namespace'
module.exports = Components.Partials ||
Components.addNamespace 'Partials', class Partials extends Neptune.Base
  ;