# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Affirmations:     require './Affirmations'    
  App:              require './App'             
  CategoryButton:   require './CategoryButton'  
  NeedEmotion:      require './NeedEmotion'     
  NeedsDashboard:   require './NeedsDashboard'  
  NeedsEmotionPage: require './NeedsEmotionPage'
  NeedStatus:       require './NeedStatus'      
  SearchBar:        require './SearchBar'       
  ShowMenu:         require './ShowMenu'        
  ShowPath:         require './ShowPath'        
  TabButton:        require './TabButton'       