// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Affirmations:   require('./Affirmations'),
  App:            require('./App'),
  CategoryButton: require('./CategoryButton'),
  NeedsDashboard: require('./NeedsDashboard'),
  NeedStatus:     require('./NeedStatus'),
  SearchBar:      require('./SearchBar'),
  ShowMenu:       require('./ShowMenu'),
  ShowPath:       require('./ShowPath'),
  TabBar:         require('./TabBar')
});
require('./Pages');
require('./Partials');
require('./Widgets');