# generated by Neptune Namespaces v2.x.x
# file: NeedsAndEmotions/App/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:             require './App'            
  CategoryButton:  require './CategoryButton' 
  SearchBar:       require './SearchBar'      
  SetStatusWidget: require './SetStatusWidget'
  ShowMenu:        require './ShowMenu'       
  ShowPath:        require './ShowPath'       
  TabButton:       require './TabButton'      