# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/App/Components/namespace.coffee

App = require '../namespace'
module.exports = App.Components ||
App.addNamespace 'Components', class Components extends Neptune.Base
  ;