// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
require('./Pages/namespace');
require('./Partials/namespace');
require('./Widgets/namespace');