// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:           require('./Main'),
  StandardImport: require('./StandardImport'),
  StyleProps:     require('./StyleProps')
});
require('./Components');
require('./Models');