# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/App/index.coffee

module.exports = require './namespace'
.includeInNamespace require './App'
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'
require './Models'