# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/App/namespace.coffee

NeedsAndEmotions = require '../namespace'
module.exports = NeedsAndEmotions.App ||
NeedsAndEmotions.addNamespace 'App', class App extends Neptune.Base
  ;