// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/namespace.js

module.exports = require('../namespace').addNamespace(
  'App',
  class App extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');