# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/namespace.coffee

module.exports = (require '../namespace').addNamespace('App', class App extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'