# generated by Neptune Namespaces v2.x.x
# file: NeedsAndEmotions/App/namespace.coffee

NeedsAndEmotions = require '../namespace'
module.exports = NeedsAndEmotions.App ||
NeedsAndEmotions.addNamespace 'App', class App extends Neptune.Base
  ;
require './Components/namespace';
require './Models/namespace'