# generated by Neptune Namespaces v0.5
# file: nvc/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Nvc ||
Neptune.addNamespace 'Nvc', class Nvc extends Neptune.Base
  ;