# generated by Neptune Namespaces v1.x.x
# file: nvc/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Nvc ||
Neptune.addNamespace 'Nvc', class Nvc extends Neptune.Base
  ;