# generated by Neptune Namespaces
# file: nvc/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Nvc ||
class Neptune.Nvc extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Nvc"

Neptune.addNamespace Neptune.Nvc