// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  History:   require('./History'),
  NavState:  require('./NavState'),
  Note:      require('./Note'),
  Status:    require('./Status'),
  ViewState: require('./ViewState')
});