# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/App/Models/index.coffee

module.exports = require './namespace'
.addModules
  Selected: require './Selected'
  Status:   require './Status'  