# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/App/Models/namespace.coffee

App = require '../namespace'
module.exports = App.Models ||
App.addNamespace 'Models', class Models extends Neptune.Base
  ;