# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/Data/index.coffee

module.exports = require './namespace'
.addModules
  Needs:            require './needs'           
  NegativeEmotions: require './NegativeEmotions'
  Nvc:              require './nvc'             
  PositiveEmotions: require './PositiveEmotions'
  Tools:            require './Tools'           