# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/Data/namespace.coffee

NeedsAndEmotions = require '../namespace'
module.exports = NeedsAndEmotions.Data ||
NeedsAndEmotions.addNamespace 'Data', class Data extends Neptune.Base
  ;