# generated by Neptune Namespaces
# file: nvc/app/styles/index.coffee

module.exports =
Styles            = require './namespace'
Styles.StyleProps = require './style_props'
Styles.finishLoad(
  ["StyleProps"]
)