# generated by Neptune Namespaces v1.x.x
# file: nvc/app/styles/namespace.coffee

App = require '../namespace'
module.exports = App.Styles ||
App.addNamespace 'Styles', class Styles extends Neptune.Base
  ;