# generated by Neptune Namespaces
# file: nvc/app/styles/namespace.coffee

App = require '../namespace'
module.exports = App.Styles ||
class App.Styles extends Neptune.Base
  @namespace: App
  @namespacePath: "Neptune.Nvc.App.Styles"

App.addNamespace App.Styles