# generated by Neptune Namespaces
# this file: src/boiler_plate/app/index.coffee

module.exports =
App            = require './namespace'
App.Components = require './components'
App.Main       = require './main'
App.finishLoad(
  ["Main"]
)