# generated by Neptune Namespaces
# file: src/boiler_plate/app/namespace.coffee

BoilerPlate = require '../namespace'
module.exports = BoilerPlate.App ||
class BoilerPlate.App extends Neptune.Base
  @namespace: BoilerPlate
  @namespacePath: "Neptune.BoilerPlate.App"

BoilerPlate.addNamespace BoilerPlate.App