# generated by Neptune Namespaces
# file: src/boiler_plate/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.BoilerPlate ||
class Neptune.BoilerPlate extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.BoilerPlate"

Neptune.addNamespace Neptune.BoilerPlate