# generated by Neptune Namespaces
# this file: src/boiler_plate/app/components/index.coffee

module.exports =
Components     = require './namespace'
Components.App = require './app'
Components.finishLoad(
  ["App"]
)