# generated by Neptune Namespaces
# file: src/boiler_plate/app/components/namespace.coffee

App = require '../namespace'
module.exports = App.Components ||
class App.Components extends Neptune.Base
  @namespace: App
  @namespacePath: "Neptune.BoilerPlate.App.Components"

App.addNamespace App.Components