# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  NeedStatusBitmap: require './NeedStatusBitmap'
  PillButton:       require './PillButton'      
  TabButton:        require './TabButton'       