// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Components/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  NeedStatusBitmap: require('./NeedStatusBitmap'),
  PillButton:       require('./PillButton'),
  TabButton:        require('./TabButton')
});