# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Widgets/namespace.coffee

module.exports = (require '../namespace').addNamespace('Widgets', class Widgets extends Neptune.PackageNamespace)
