# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Pages/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  HomePage:         require './HomePage'        
  NeedsEmotionPage: require './NeedsEmotionPage'
  StandardImport:   require './StandardImport'  