// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Components/Pages/index.js

(module.exports = require('./namespace'))

.addModules({
  History:          require('./History'),
  Home:             require('./Home'),
  ImportExport:     require('./ImportExport'),
  NeedsEmotionPage: require('./NeedsEmotionPage'),
  Notes:            require('./Notes'),
  StandardImport:   require('./StandardImport')
});