# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Pages/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pages', class Pages extends Neptune.PackageNamespace)
