# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Partials/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  NeedEmotion: require './NeedEmotion'
  NeedStrip:   require './NeedStrip'  