// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/App/Components/Partials/index.js

(module.exports = require('./namespace'))

.addModules({
  HistoryEntry:  require('./HistoryEntry'),
  NeedEmotion:   require('./NeedEmotion'),
  NeedStrip:     require('./NeedStrip'),
  NeedStripCore: require('./NeedStripCore')
});