# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/App/Components/Partials/namespace.coffee

module.exports = (require '../namespace').addNamespace('Partials', class Partials extends Neptune.PackageNamespace)
