// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./NeedsAndEmotions'))
.addModules({
  StandardImport: require('./StandardImport')
});
require('./App');
require('./Data');
require('./Pipelines');