# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/index.coffee

module.exports = require './namespace'
.includeInNamespace require './NeedsAndEmotions'
require './App'
require './Data'