# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './NeedsAndEmotions'
.addModules
  StandardImport: require './StandardImport'
require './App'
require './Data'
require './Pipelines'