# generated by Neptune Namespaces v1.x.x
# file: NeedsAndEmotions/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.NeedsAndEmotions ||
Neptune.addNamespace 'NeedsAndEmotions', class NeedsAndEmotions extends Neptune.Base
  ;