// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'NeedsAndEmotions',
  (class NeedsAndEmotions extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./App/namespace');
require('./Data/namespace');
require('./Pipelines/namespace');