# generated by Neptune Namespaces v2.x.x
# file: NeedsAndEmotions/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.NeedsAndEmotions ||
Neptune.addNamespace 'NeedsAndEmotions', class NeedsAndEmotions extends Neptune.Base
  ;
require './App/namespace';
require './Data/namespace'