# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'NeedsAndEmotions', class NeedsAndEmotions extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './App/namespace';
require './Data/namespace';
require './Pipelines/namespace'