# generated by Neptune Namespaces
# file: nvc/app/components/pages/index.coffee

module.exports =
Pages         = require './namespace'
Pages.ShowMap = require './show_map'
Pages.finishLoad(
  ["ShowMap"]
)