# generated by Neptune Namespaces v0.3.0
# file: nvc/app/components/pages/namespace.coffee

Components = require '../namespace'
module.exports = Components.Pages ||
Components.addNamespace 'Pages', class Pages extends Neptune.Base
  ;