# generated by Neptune Namespaces
# file: nvc/app/components/pages/namespace.coffee

Components = require '../namespace'
module.exports = Components.Pages ||
class Components.Pages extends Neptune.Base
  @namespace: Components
  @namespacePath: "Neptune.Nvc.App.Components.Pages"

Components.addNamespace Components.Pages