// generated by Neptune Namespaces v4.x.x
// file: NeedsAndEmotions/Pipelines/index.js

(module.exports = require('./namespace'))

.addModules({
  Affirmation:    require('./Affirmation'),
  AffirmationDay: require('./AffirmationDay')
});