# generated by Neptune Namespaces v3.x.x
# file: NeedsAndEmotions/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Affirmation:    require './Affirmation'   
  AffirmationDay: require './AffirmationDay'