# generated by Neptune Namespaces
# file: nvc/app/index.coffee

module.exports =
App            = require './namespace'
App.Main       = require './main'
App.Components = require './components'
App.Models     = require './models'
App.finishLoad(
  ["Main"]
)