# generated by Neptune Namespaces v1.x.x
# file: nvc/app/index.coffee

module.exports = require './namespace'
.addModules
  Main: require './main'
require './components'
require './models'
require './styles'