# generated by Neptune Namespaces v0.3.0
# file: nvc/app/index.coffee

(module.exports = require './namespace')
.addModules
  Main: require './main'
require './components'
require './data'
require './models'
require './styles'