# generated by Neptune Namespaces
# file: nvc/app/namespace.coffee

Nvc = require '../namespace'
module.exports = Nvc.App ||
class Nvc.App extends Neptune.Base
  @namespace: Nvc
  @namespacePath: "Neptune.Nvc.App"

Nvc.addNamespace Nvc.App