# generated by Neptune Namespaces
# file: nvc/app/data/namespace.coffee

App = require '../namespace'
module.exports = App.Data ||
class App.Data extends Neptune.Base
  @namespace: App
  @namespacePath: "Neptune.Nvc.App.Data"

App.addNamespace App.Data